# Generated by Django 4.2.6 on 2023-10-24 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=500)),
                ('Is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=500)),
                ('Is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Appointment_Date', models.DateTimeField()),
                ('Is_active', models.BooleanField(default=True)),
                ('Counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.counsellor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
